# Dockerfile
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

### puerto para exponer el servicio 5000 y el 8000 para prometheus
EXPOSE 5000
EXPOSE 8000

CMD ["python", "app.py"]
