name: Build an push docker image yo docker hub

on: push
jobs:
    push_to_registry:
        name: Push docker image yo docker hub
        runs-on: ubuntu-latest
        steps:
            - name: check out th repo
              uses: actions/checkout@v3

            - name: login to docker hub
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}

            - name: Build and push docker images
              uses: docker/build-push-action@v4
              with:
                #directorio en donde se encuentra el dockerfile
                context: helloword/
                push: true
                tags: abelucci/test:latest